### ISSUE TITLE
File Templating

### ISSUE THREAD

**Issue by bruno-delfino1995** [bruno-delfino1995/kct#6]
There're types of applications that depend on configuration files that may be variable to their deployment setup or other criteria. To support these kinds of applications, we should have a mechanism for file templating that would inject the given values into a template engine. The render would package these compiled templates as an array of paths bound to another TLA on the main function.

This mechanism would act as a templated alternative to [`.Files` in Helm](https://helm.sh/docs/chart_template_guide/accessing_files/).

**Comment by passionlord** [comment]
#7
